### ISSUE TITLE
Getting error while running UT: ReferenceError: cov_2mzv4qbkmp is not defined

### ISSUE THREAD

**Issue by jainshravan123** [andywer/threads.js#105]
I used Thread module. It's working perfectly and manually tested a lot of times but now i started writing UT and It started throwing the following error. 

```
err :  ReferenceError: cov_2mzv4qbkmp is not defined
    at module.exports (evalmachine.<anonymous>:1:49)
    at process.<anonymous> (/Users/shravanjain/Work/project/node_modules/threads/lib/worker.node/slave.js:88:20)
    at process.emit (events.js:182:13)
    at processEmit [as emit] (/Users/shravanjain/Work/project/node_modules/signal-exit/index.js:155:32)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Can someone please help in fixing this error?

**Comment by andywer** [comment]
Hey @jainshravan123.

I guess "UT" means "unit tests"? I am sorry, but the 0.x versions are about to be deprecated and I don't know a simple fix for your issue either.

My best advise right now is: **Try disabling code coverage tracking for now. If that doesn't help, switch to version 1.0 as soon as possible.**

Right now there is only an early alpha of v1.0 available, but I will publish an updated pre-release this week. It comes with a whole new API (see #100), but it solves a bunch of long-standing issues and is just generally less confusing to use.
