### ISSUE TITLE
Not working with --enable-source-maps

### ISSUE THREAD

**Issue by skrylnikov** [andywer/threads.js#173]
run script: 
`node -r ts-node/register --enable-source-maps index.ts`

exception:

```
path/node_modules/threads/dist/master/implementation.node.js:51
    const parentCallSite = callsites_1.default().find((callsite) => {
                                                 ^
TypeError: callsites_1.default(...).find is not a function
    at rebaseScriptPath (path/node_modules/threads/dist/master/implementation.node.js:51:50)
    at resolveScriptPath (path/node_modules/threads/dist/master/implementation.node.js:63:27)
    at new Worker (path/node_modules/threads/dist/master/implementation.node.js:74:40)
    at path/src/csv/index.ts:4:51
        -> path/src/csv/index.ts:3:31
    at path/node_modules/threads/dist/master/pool.js:85:15
    at Array.map (<anonymous>)
    at spawnWorkers (path/node_modules/threads/dist/master/pool.js:84:31)
    at Object.PoolConstructor [as Pool] (path/node_modules/threads/dist/master/pool.js:99:21)
    at Object.<anonymous> (path/src/csv/index.ts:4:24)
        -> path/src/csv/index.ts:3:14
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

main.ts:
```js
import { spawn, Worker, Pool } from 'threads';

const pool = Pool(() => spawn(new Worker('./worker.ts')), 4);
```

worker.ts:
```ts
import { expose } from 'threads/worker';

const start = ()=>{
  console.log('start worker');
  
};

export type Start = typeof start;

expose(start);
 
```

**Comment by andywer** [comment]
Hey @skrylnikov! Thanks for reporting, that really does look weird.

Can you confirm that it works without `--enable-source-maps` and can you `console.log(callsites_1)` in the line above the one where the error is thrown, please?

**Comment by skrylnikov** [comment]
Yes, it works without `--enable-source-maps`.
I think I find problem. It occurs in callsites. Callsites use Error.prepareStackTrace, But Error.prepareStackTrace not work with `--enable-source-maps`.
 https://github.com/nodejs/node/issues/29994

**Comment by andywer** [comment]
Good catch. Let's open an issue at the `callsites` repo then. Can you tell me what the callsites call returns when the source maps are on? Would be an important detail when we open the issue at their repo.

**Comment by andywer** [comment]
Ping. Please see above 👆😉

**Comment by andywer** [comment]
Closing, due to inactivity.
