### ISSUE TITLE
TypeError: process.send is not a function

### ISSUE THREAD

**Issue by crimson-med** [andywer/threads.js#266]
I have just tried using this with node `v12.9.1` I have also tried installing `tiny-workers`

I want the wokers to work in the background as they 

Pathfinder.ts

```typescript
import { spawn, Thread, Worker } from "threads"
import { Pathfinder } from '../workers/GPathfinder'
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient()

export class BackgroundWorker {
    constructor() {
        
    }

    async pathfinder() {
        const pathfinder = await spawn<GPathfinder>(new Worker("./../workers/GPathfinder"));
        await pathfinder.findAllFilePath(prisma);
        await  Thread.terminate(pathfinder)
    }
}
```

workers/GPathfinder.ts

```typescript
import { PrismaClient } from "@prisma/client"

const pathfinder = {
    /**
     * Find the path for all files in the database
     * @param prisma 
     */
    async findAllFilePath(prisma: PrismaClient) {
        const files = await prisma.file.findMany({
            where: {
                NOT: {
                    name: null
                }
            }
        })
        console.log(`I'm in the worker`)
        console.log(`found: ${files.length}`)
    }
}
export type Pathfinder = typeof pathfinder;
expose(pathfinder)
```

main.ts

```typescript
import { BackgroundWorker } from '../workers/BackgroundWorker'
async scan () {
    const bg = new BackgroundWorker()
    bg.pathfinder()
}
scan()
```

full error:

```
/private/var/folders/d8/j9fgywc164n4n99q375ls6zr0000gn/T/ts-node-dev-hook-3370528567272091.js:40
  process.send({
          ^

TypeError: process.send is not a function
    at compile (/private/var/folders/d8/j9fgywc164n4n99q375ls6zr0000gn/T/ts-node-dev-hook-3370528567272091.js:40:11)
    at Module.m._compile (/private/var/folders/d8/j9fgywc164n4n99q375ls6zr0000gn/T/ts-node-dev-hook-3370528567272091.js:57:36)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at require.extensions.<computed> (/private/var/folders/d8/j9fgywc164n4n99q375ls6zr0000gn/T/ts-node-dev-hook-3370528567272091.js:59:14)
    at Object.require.extensions.<computed> [as .ts] (/Users/xxx/yyy/zzz/backend/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at [worker eval]:3:5
[ERROR] 18:51:25 TypeError: process.send is not a function
```

**Comment by andywer** [comment]
Hey @crimson-med. threads.js doesn't ever call `process.send()` and neither does any of its few dependencies, I think. Seems to originate from some other dependency of yours.

Feel free to re-open if you can make sure that it's actually caused by threads.js (ideally with a minimal sample repo to reproduce the issue).

**Comment by crimson-med** [comment]
@andywer i will look at pushing a repo with the issue but it is defo coming from threads if I comment the class creation and function call in main.ts then no more error.
