### ISSUE TITLE
Debugging with ts-node and visual studio

### ISSUE THREAD

**Issue by tuturis** [andywer/threads.js#274]
There seems to be an issue with running threads.js with `node -r ts-node/register`. 
Description of how the issue appears:
Launching application through VS Code debugger that has threads.js method call that spawns worker a new worker.
After the first call to such method, everything works fine - worker returns. Subsequent calls throws
```
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (E:\something\node_modules\threads\dist\master\spawn.js:34:53)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
``` 

Details:
tsconfig.json
```
{
  "compilerOptions": {
    "skipLibCheck": true,
    "lib": [
      "dom",
      "es5",
      "es6",
      "es7",
      "es2015",
      "es2016",
      "es2017",
      "es2018",
      "esnext"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "pretty": true,
    "sourceMap": false,
    "target": "es6",
    "outDir": "./dist",
    "baseUrl": "./",
    "declaration": true,
    },
    "forceConsistentCasingInFileNames": false,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "strict": true,
    "strictNullChecks": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "noUnusedLocals": false,
    "esModuleInterop": true,
    "typeRoots": [
      "./node_modules/@types",
      "./src/@types"
    ]
  },
  "include": [
    "./src/*.ts",
    "./src/**/*.ts",
    "./src/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "typeAcquisition": {
    "enable": true
  }
}
```
vs code debuggers launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "API",
      "type": "node",
      "request": "launch",
      "args": [
        "${workspaceFolder}/src/Server.ts"
      ],
      "runtimeArgs": [
        "-r",
        "ts-node/register"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "internalConsoleOptions": "openOnSessionStart",
    }
  ]
}
```
Sample code 
Controller with the worker method
```
export default class Controller {
    worker_pool: WorkerPool.Pool<WorkerPool.ModuleThread<Worker>>
    constructor() {
        this.story_worker_pool = Pool(() => spawn<Worker>(new Worker("./worker.worker")))
    }
   async method() {
        return this.worker_pool.queue(async worker => {
            processed_items = await worker.processItems(items)
        })
   }
}
```
worker
```
export class Worker implements WorkerModule<any>  {
    [x: string]: WorkerFunction;

    public processItems(items): any[] {
        items.map((story, index) => {
            // do math
        });
        return items
    }
}
expose(StoryWorker as any)
```
How this issue could be resolved? Everything works fine with the sample code after building the source code and running it with node

**Comment by andywer** [comment]
Hey @tuturis.

Can't really tell as I tried to use the VS code debugger like three times in my life without much success, so I just didn't try again. What you can do, though, is setting this environment variable to enable debug logging: `DEBUG=threads*`

Apart from that… maybe someone else has an idea?

**Comment by andywer** [comment]
Thanks, @Dobloq!

I see… I am not surprised that it fails with that spawn timeout error (if the debugger halts the new thread immediately, of course it cannot tell the main thread that it has initialized), I am rather surprised that it works once at all.

@tuturis Maybe you continued / skipped that breakpoint in the worker quickly enough when it was first hit and then on subsequent calls the debugger just kept the thread on hold?

**Comment by eliellis** [comment]
Could be related: https://github.com/microsoft/vscode/issues/125451 
Seems like it's been closed as well.
