### ISSUE TITLE
Refused to create a worker

### ISSUE THREAD

**Issue by aminya** [andywer/threads.js#284]
I am trying to run threads in an Atom package (an electron app), but this is the error I am getting when I try to implement a simple example:

The code is here: https://github.com/aminya/ide-json/tree/master/lib

Errors:
Web worker implementation:
```js
C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38 Refused to create a worker from 'blob:file:///844dc93f-470b-4d1e-a82f-2ec4c5d8d087' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

WebWorker @ C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38
(anonymous) @ main.js:11
step @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:17
(anonymous) @ main.js:17
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217
C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38 Uncaught (in promise) DOMException: Failed to construct 'Worker': Access to the script at 'blob:file:///844dc93f-470b-4d1e-a82f-2ec4c5d8d087' is denied by the document's Content Security Policy.
    at new WebWorker (C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38:13)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:11:42
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at new Promise (<anonymous>)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:18)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:24)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:147498)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.49.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3308425)
    at Package.activateNow (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296409)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296187
    at Package.measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3293797)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296047
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3295990)
    at PackageManager.activatePackage (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382943)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382559
    at Config.transactAsync (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:332207)
    at PackageManager.activatePackages (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382509)
    at PackageManager.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382059)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:757178
WebWorker @ C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38
(anonymous) @ main.js:11
step @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:17
(anonymous) @ main.js:17
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217

```

Node implementation:
```js
internal/worker.js:100 Uncaught (in promise) Error: The V8 platform used by this instance of Node does not support creating Workers
    at new Worker (internal/worker.js:100:21)
    at new Worker (C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.node.js:111:17)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:11:42
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at new Promise (<anonymous>)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:18)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:24)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:147498)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.49.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3308425)
    at Package.activateNow (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296409)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296187
    at Package.measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3293797)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296047
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3295990)
    at PackageManager.activatePackage (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382943)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382559
    at Config.transactAsync (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:332207)
    at PackageManager.activatePackages (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382509)
    at PackageManager.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382059)
Worker @ internal/worker.js:100
Worker @ C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.node.js:111
(anonymous) @ main.js:11
step @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:17
(anonymous) @ main.js:17
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217

```

**Comment by andywer** [comment]
Hey @aminya! Thanks for the detailed error output – that helps.

So Electron is based on a node.js version that is compiled with a V8 without worker threads support, as far as I can tell. If that's true, there is nothing you can do about that…

Which leaves you still with the web workers in the web view. The interesting piece of information here is:
```
DOMException: Failed to construct 'Worker': Access to the script at 'blob:file:///844dc93f-470b-4d1e-a82f-2ec4c5d8d087' is denied by the document'
```

The URL passed to the `Worker` constructor is somehow messed up. It has two protocols set (`blob` and `file`). I am quite busy atm, so many you can have a look, too, why that happens? I will try to look into it, too.

**Comment by andywer** [comment]
PS: Can you also share your code spawning the web worker?

**Comment by aminya** [comment]
Thank you for your answer. Here is the code:
https://github.com/aminya/ide-json/blob/524f9d384c430f3d714248a468e7ff99ab4a0981/lib/main.js#L3

Just change `"threads/dist/master/implementation.browser"` to `"threads/dist/master/implementation.node"` for using the node implementation.

**Comment by andywer** [comment]
Ohh wow, that's dark - but does the job… Never even occurred to me that users might start to deep-import those platform-specific files directly 😅

Are you sure this is the code you ran when the error mentioned above happened? The prepended `blob:` protocol on the worker URL looks on first glance as if you were using a `BlobWorker`.

**Comment by aminya** [comment]
> Ohh wow, that's dark - but does the job… Never even occurred to me that users might start to deep-import those platform-specific files directly 😅

I just did this to workaround #285.


Here is the output for the code that uses `BlobWorker`:
```js
import { spawn } from "threads"
import * as BrowserImplementation from "threads/dist/master/implementation.browser"
const implementation = BrowserImplementation
getWorkerImplementation = implementation.getWorkerImplementation
const Worker = getWorkerImplementation().blob
```


```js
C:\Users\myproject\ide-json\node_modules\threads\dist\master\implementation.browser.js:45 Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at new BlobWorker (C:\Users\myproject\ide-json\node_modules\threads\dist\master\implementation.browser.js:45:36)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:23:30
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:26:2)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:26:2
    at new Promise (<anonymous>)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:26:2
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:28:18)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:28:24)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:147498)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.49.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3308425)
    at Package.activateNow (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296409)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296187
    at Package.measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3293797)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296047
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3295990)
    at PackageManager.activatePackage (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382943)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382559
    at Config.transactAsync (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:332207)
    at PackageManager.activatePackages (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382509)
    at PackageManager.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382059)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:757178
BlobWorker @ C:\Users\myproject\ide-json\node_modules\threads\dist\master\implementation.browser.js:45
(anonymous) @ main.js:23
step @ main.js:26
(anonymous) @ main.js:26
(anonymous) @ main.js:26
(anonymous) @ main.js:28
(anonymous) @ main.js:28
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217
index.js:175 Using an InMemoryStrategy strategy for storing tokens. The tokens will only be stored for the current window.
InMemoryStrategy @ <embedded>:14
createStrategy @ <embedded>:14
async function (async)
createStrategy @ <embedded>:14
getStrategy @ <embedded>:14
getToken @ <embedded>:14
getToken @ <embedded>:14
loadMentionableUsers @ <embedded>:14
(anonymous) @ <embedded>:14
loadUsersFromGraphQL @ <embedded>:14
loadUsers @ <embedded>:14
didUpdate @ <embedded>:14
_refreshModelData @ <embedded>:14
async function (async)
_refreshModelData @ <embedded>:14
refreshModelData @ <embedded>:14
(anonymous) @ <embedded>:14
simpleDispatch @ <embedded>:11
emit @ <embedded>:11
transition @ <embedded>:14
transitionTo @ <embedded>:14
start @ <embedded>:14
async function (async)
start @ <embedded>:14
transition @ <embedded>:14
transitionTo @ <embedded>:14
Repository @ <embedded>:14
(anonymous) @ <embedded>:14
WorkdirContext @ <embedded>:14
add @ <embedded>:14
set @ <embedded>:14
getNextContext @ <embedded>:11
async function (async)
getNextContext @ <embedded>:11
updateActiveContext @ <embedded>:11
execute @ <embedded>:14
processTask @ <embedded>:14
processQueue @ <embedded>:14
push @ <embedded>:14
scheduleActiveContextUpdate @ <embedded>:11
activate @ <embedded>:11
async function (async)
activate @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217


```
