### ISSUE TITLE
Node JS dependencies bug

### ISSUE THREAD

**Issue by zandercodes** [andywer/threads.js#99]
I'm trying to use the thread pool in Node.js to speed a for loop.
The problem is: I use the node module resemble.js
When import this module in the thread give a reference error for the module.
```
Job error: ReferenceError: FileReader is not defined
    at loadImageData (/Users/zandercodes/WebstormProjects/testproject/node_modules/resemblejs/resemble.js:325:17)
    at compare (/Users/zandercodes/WebstormProjects/testproject/node_modules/resemblejs/resemble.js:822:13)
    at wrapper (/Users/zandercodes/WebstormProjects/testproject/node_modules/resemblejs/resemble.js:942:25)
    at Object.onComplete (/Users/zandercodes/WebstormProjects/testproject/node_modules/resemblejs/resemble.js:945:21)
    at resemble.compare (/Users/zandercodes/WebstormProjects/testproject/node_modules/resemblejs/resemble.js:1035:17)
    at module.exports (evalmachine.<anonymous>:5:7)
    at process.<anonymous> (/Users/zandercodes/WebstormProjects/testproject/node_modules/threads/lib/worker.node/slave.js:84:20)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
```

Where is the error because without thread it works without problems?

**Comment by andywer** [comment]
Sorry for the late response, @zandercodes.

Not sure if I can follow. There is no `FileReader` API in node, that's a browser thing...

**Comment by zandercodes** [comment]
I have fix that with an custom module.

Custom Module Class:
```
const canvas = require('canvas');
const imageType = require('image-type');

function overrideWindow() {
  const doc = {};
  doc.createElement = function createElement(tag) {
    return (tag !== 'canvas')
      ? false
      : new canvas();
  };
  return {
    document: doc
  };
}

function overrideFileReader() {
  const FileReader = function FileReader() { };
  FileReader.prototype.readAsDataURL = function readAsDataURL(buffer) {
    this.onload({
      target: {
        result: "data:image/" + imageType(buffer) + ";base64," + buffer.toString('base64') + ""
      }
    });
  };
  return FileReader;
}

function overrideImage() {
  const Image = canvas.Image;
  Image.prototype.setAttribute = function setAttribute() { };
  return Image;
}

module.exports = function exports() {
  if (typeof window === 'undefined') {
    global.window = overrideWindow();
  }
  if (typeof FileReader === 'undefined') {
    global.FileReader = overrideFileReader();
  }
  if (typeof Image === 'undefined') {
    global.Image = overrideImage();
  }
  const compare = require('resemblejs').compare;
  return compare.apply(this, arguments);
};
```

and main class:
```
let orgi = base64_encode("./img/" + files[i]);
    pool.run((input, done, error) => {
      const { filename, orgi, image, options, __dirname } = input;
      const compare = require(__dirname + "/Test.js");
      let orgiN = Buffer(orgi ,"base64");
      let imgN = Buffer(image ,"base64");

      compare(orgiN, imgN, options, (err, data) => {
        if (err) {
          console.log(err);
          error(err);
        } else {
          done({ name: filename, misMatchPercentage: data.misMatchPercentage });
        }
      });
    }).send({ filename: files[i], orgi, image, options, __dirname: __dirname, worker: i + 1 });
    console.log("Start worker: ", i + 1);
  }
```

**Comment by andywer** [comment]
That is because the thread code will have its own scope, so you will need to repeat that monkey-patching in the thread:

```js
if (typeof FileReader === 'undefined') {
  global.FileReader = overrideFileReader();
}
```

**Comment by zandercodes** [comment]
Thanks
